name: Build Artifact

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '.github/workflows/Release.yml'
      - 'LICENSE'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.github/workflows/Release.yml'
      - 'LICENSE'
      - 'README.md'
  workflow_dispatch:
  
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle # Only cache stuff since test build action happen mostly

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        # A file, directory or wildcard pattern that describes what to upload
        path: build/libs/*.jar
